#!/usr/bin/env python3
"""
Config - Module de configuration centralisée
===========================================

Ce module exporte toute la configuration de TradeSim.
La configuration est centralisée pour faciliter la maintenance.

Auteur: Assistant IA
Date: 2024-08-02
"""

# Imports de la configuration depuis le fichier config.py
from .config import (
    # Simulation
    NOMBRE_TOURS,
    N_ENTREPRISES_PAR_TOUR,
    DUREE_PAUSE_ENTRE_TOURS,
    PROBABILITE_SELECTION_ENTREPRISE,
    
    # Debug
    DEBUG_MODE,
    
    # Logs
    BASE_DIR,
    LOG_DIR,
    FICHIER_LOG,
    FICHIER_LOG_HUMAIN,
    EVENT_LOG_JSON,
    EVENT_LOG_HUMAIN,
    
    # Événements
    RECHARGE_BUDGET_MIN,
    RECHARGE_BUDGET_MAX,
    REASSORT_QUANTITE_MIN,
    REASSORT_QUANTITE_MAX,
    INFLATION_POURCENTAGE_MIN,
    INFLATION_POURCENTAGE_MAX,
    PENALITE_INFLATION_PRODUIT_EXISTANT,
    DUREE_PENALITE_INFLATION,
    DUREE_RETOUR_INFLATION,
    DUREE_BAISSE_INFLATION,
    POURCENTAGE_FINAL_INFLATION,
    PROBABILITE_DESACTIVATION,
    PROBABILITE_REACTIVATION,
    TICK_INTERVAL_EVENT,
    PROBABILITE_EVENEMENT,
    RECHARGE_FOURNISSEUR_INTERVAL,
    PROBABILITE_RECHARGE_FOURNISSEUR,
    PROBABILITE_RECHARGE_PRODUIT,
    RECHARGE_QUANTITE_MIN,
    RECHARGE_QUANTITE_MAX,
    
    # Entreprises
    TYPES_PRODUITS_PREFERES_MIN,
    TYPES_PRODUITS_PREFERES_MAX,
    QUANTITE_ACHAT_MIN,
    QUANTITE_ACHAT_MAX,
    QUANTITE_ACHAT_PRIX_ELEVE_MIN,
    QUANTITE_ACHAT_PRIX_ELEVE_MAX,
    SEUIL_PRIX_ELEVE,
    BUDGET_ENTREPRISE_MIN,
    BUDGET_ENTREPRISE_MAX,
    
    # Produits
    PRIX_PRODUIT_MIN,
    PRIX_PRODUIT_MAX,
    NOMBRE_PRODUITS_DEFAUT,
    PRODUITS_ACTIFS_MIN,
    PRODUITS_ACTIFS_MAX,
    TYPES_PRODUITS_DISPONIBLES,
    FACTEUR_PRIX_STOCK_REFERENCE,
    FACTEUR_PRIX_STOCK_VARIATION,
    FACTEUR_PRIX_RANDOM_MIN,
    FACTEUR_PRIX_RANDOM_MAX,
    
    # Configuration par défaut
    DEFAULT_CONTINENT, VALID_CONTINENTS, validate_continent,
    
    # Configuration monitoring
    METRICS_ENABLED,
    METRICS_COLLECTION_INTERVAL,
    METRICS_EXPORTER_PORT,
    METRICS_EXPORTER_HOST,
    METRICS_PROMETHEUS_PORT,
    METRICS_GRAFANA_PORT,
    METRICS_SYSTEM_ENABLED,
    METRICS_SYSTEM_INTERVAL,
    METRICS_LABELS_ENABLED,
    METRICS_LABELS_CONTINENT,
    METRICS_LABELS_PRODUIT_TYPE,
    
    # Configuration des IDs uniques
    ID_FORMAT,
    ID_SESSION_FORMAT,
    MAX_COUNTER,
    VALID_ACTION_TYPES,
    
    # Configuration des optimisations
    BATCH_LOG_SIZE,
    CACHE_MAX_SIZE,
    COMPRESSION_DAYS,
    INDEX_ENABLED,
    VALIDATION_ENABLED,
    REALTIME_MONITORING,
    PERFORMANCE_THRESHOLD,
    
    # Seuils d'alerte temps réel
    ALERT_BUDGET_CRITIQUE,
    ALERT_STOCK_CRITIQUE,
    ALERT_ERROR_RATE,
    
    # Configuration des métriques
    METRICS_COLLECTION_INTERVAL,
    METRICS_RETENTION_DAYS,
    
    # Configuration Latency & Throughput
    LATENCY_COLLECTION_INTERVAL,
    LATENCY_HISTOGRAM_BUCKETS,
    LATENCY_HISTORY_SIZE,
    THROUGHPUT_WINDOW_SIZE,
    THROUGHPUT_MIN_INTERVAL,
    LATENCY_WARNING_THRESHOLD,
    LATENCY_CRITICAL_THRESHOLD,
    THROUGHPUT_MIN_RATE,
)

# Exports publics
__all__ = [
    # Simulation
    'NOMBRE_TOURS',
    'N_ENTREPRISES_PAR_TOUR', 
    'DUREE_PAUSE_ENTRE_TOURS',
    'PROBABILITE_SELECTION_ENTREPRISE',
    
    # Debug
    'DEBUG_MODE',
    
    # Logs
    'BASE_DIR',
    'LOG_DIR',
    'FICHIER_LOG',
    'FICHIER_LOG_HUMAIN',
    'EVENT_LOG_JSON',
    'EVENT_LOG_HUMAIN',
    
    # Événements
    'RECHARGE_BUDGET_MIN',
    'RECHARGE_BUDGET_MAX',
    'REASSORT_QUANTITE_MIN',
    'REASSORT_QUANTITE_MAX',
    'INFLATION_POURCENTAGE_MIN',
    'INFLATION_POURCENTAGE_MAX',
    'PENALITE_INFLATION_PRODUIT_EXISTANT',
    'DUREE_PENALITE_INFLATION',
    'DUREE_RETOUR_INFLATION',
    'DUREE_BAISSE_INFLATION',
    'POURCENTAGE_FINAL_INFLATION',
    'PROBABILITE_DESACTIVATION',
    'PROBABILITE_REACTIVATION',
    'TICK_INTERVAL_EVENT',
    'PROBABILITE_EVENEMENT',
    'RECHARGE_FOURNISSEUR_INTERVAL',
    'PROBABILITE_RECHARGE_FOURNISSEUR',
    'PROBABILITE_RECHARGE_PRODUIT',
    'RECHARGE_QUANTITE_MIN',
    'RECHARGE_QUANTITE_MAX',
    
    # Entreprises
    'TYPES_PRODUITS_PREFERES_MIN',
    'TYPES_PRODUITS_PREFERES_MAX',
    'QUANTITE_ACHAT_MIN',
    'QUANTITE_ACHAT_MAX',
    'QUANTITE_ACHAT_PRIX_ELEVE_MIN',
    'QUANTITE_ACHAT_PRIX_ELEVE_MAX',
    'SEUIL_PRIX_ELEVE',
    'BUDGET_ENTREPRISE_MIN',
    'BUDGET_ENTREPRISE_MAX',
    
    # Produits
    'PRIX_PRODUIT_MIN',
    'PRIX_PRODUIT_MAX',
    'NOMBRE_PRODUITS_DEFAUT',
    'PRODUITS_ACTIFS_MIN',
    'PRODUITS_ACTIFS_MAX',
    'TYPES_PRODUITS_DISPONIBLES',
    'FACTEUR_PRIX_STOCK_REFERENCE',
    'FACTEUR_PRIX_STOCK_VARIATION',
    'FACTEUR_PRIX_RANDOM_MIN',
    'FACTEUR_PRIX_RANDOM_MAX',
    
    # Configuration par défaut
    'DEFAULT_CONTINENT', 'VALID_CONTINENTS', 'validate_continent',
    
    # Configuration monitoring
    'METRICS_ENABLED',
    'METRICS_COLLECTION_INTERVAL',
    'METRICS_EXPORTER_PORT',
    'METRICS_EXPORTER_HOST',
    'METRICS_PROMETHEUS_PORT',
    'METRICS_GRAFANA_PORT',
    'METRICS_SYSTEM_ENABLED',
    'METRICS_SYSTEM_INTERVAL',
    'METRICS_LABELS_ENABLED',
    'METRICS_LABELS_CONTINENT',
    'METRICS_LABELS_PRODUIT_TYPE',
    
    # Configuration des IDs uniques
    'ID_FORMAT',
    'ID_SESSION_FORMAT',
    'MAX_COUNTER',
    'VALID_ACTION_TYPES',
    
    # Configuration des optimisations
    'BATCH_LOG_SIZE',
    'CACHE_MAX_SIZE',
    'COMPRESSION_DAYS',
    'INDEX_ENABLED',
    'VALIDATION_ENABLED',
    'REALTIME_MONITORING',
    'PERFORMANCE_THRESHOLD',
    
    # Seuils d'alerte temps réel
    'ALERT_BUDGET_CRITIQUE',
    'ALERT_STOCK_CRITIQUE',
    'ALERT_ERROR_RATE',
    
    # Configuration des métriques
    'METRICS_COLLECTION_INTERVAL',
    'METRICS_RETENTION_DAYS',
    
    # Configuration Latency & Throughput
    'LATENCY_COLLECTION_INTERVAL',
    'LATENCY_HISTOGRAM_BUCKETS',
    'LATENCY_HISTORY_SIZE',
    'THROUGHPUT_WINDOW_SIZE',
    'THROUGHPUT_MIN_INTERVAL',
    'LATENCY_WARNING_THRESHOLD',
    'LATENCY_CRITICAL_THRESHOLD',
    'THROUGHPUT_MIN_RATE',
] 